#!/usr/bin/env bun

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const projectRoot = resolve(import.meta.dir, "../..");
const sourceRoot = join(projectRoot, "vendor", "wubimb-data");
const sourcePath = join(sourceRoot, "wubi86.txt");
const sourceMetadataPath = join(sourceRoot, "SOURCE.json");
const outputPath = join(projectRoot, "shared", "RimeData", "typing_wubi86.dict.yaml");
const expectedEntryCount = 53_727;

interface SourceMetadata {
  sourceSha256: string;
  commit: string;
}

// 将锁定的 MIT 五笔表转换为项目 Rime 字典，并拒绝哈希、编码或条目数量变化。
function generateDictionary(): void {
  const sourceMetadata = JSON.parse(readFileSync(sourceMetadataPath, "utf8")) as SourceMetadata;
  const sourceBuffer = readFileSync(sourcePath);
  const sourceHash = createHash("sha256").update(sourceBuffer).digest("hex");
  if (sourceHash !== sourceMetadata.sourceSha256) {
    throw new Error(`五笔源文件哈希不匹配：${sourceHash}`);
  }

  const dictionaryEntryList: string[] = [];
  for (const [lineIndex, sourceLine] of sourceBuffer.toString("utf8").split(/\r?\n/).entries()) {
    if (!sourceLine.trim()) continue;
    const tokenList = sourceLine.split("\t");
    if (tokenList.length !== 3) {
      throw new Error(`五笔源文件第 ${lineIndex + 1} 行字段数量无效`);
    }
    const [codeText, textValue, weightText] = tokenList;
    if (!/^[a-y]{1,4}$/.test(codeText)) {
      throw new Error(`五笔源文件第 ${lineIndex + 1} 行编码无效：${codeText}`);
    }
    if (!textValue || /\s/.test(textValue)) {
      throw new Error(`五笔源文件第 ${lineIndex + 1} 行正文无效`);
    }
    if (!/^\d+$/.test(weightText)) {
      throw new Error(`五笔源文件第 ${lineIndex + 1} 行权重无效`);
    }
    dictionaryEntryList.push(`${textValue}\t${codeText}\t${weightText}`);
  }
  if (dictionaryEntryList.length !== expectedEntryCount) {
    throw new Error(`五笔词典条目数异常：${dictionaryEntryList.length}`);
  }

  const outputText = [
    "# Rime dictionary",
    "# encoding: utf-8",
    "# Generated by scripts/rime/generate-wubi86-dictionary.ts.",
    `# Source: tenfyzhong/wubimb ${sourceMetadata.commit}, MIT; see vendor/wubimb-data/.`,
    "",
    "---",
    "name: typing_wubi86",
    'version: "2026.08.05"',
    "sort: by_weight",
    "use_preset_vocabulary: false",
    "columns:",
    "  - text",
    "  - code",
    "  - weight",
    "...",
    "",
    ...dictionaryEntryList,
    "",
  ].join("\n");
  writeFileSync(outputPath, outputText);
  console.log(`已生成 ${dictionaryEntryList.length} 条 MIT 五笔词条：${outputPath}`);
}

generateDictionary();
