#!/usr/bin/env bun

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const projectRoot = resolve(import.meta.dir, "../..");
const sourceRoot = join(projectRoot, "vendor", "aosp-pinyinime-data");
const sourcePath = join(sourceRoot, "rawdict_utf16_65105_freq.txt");
const sourceMetadataPath = join(sourceRoot, "SOURCE.json");
const outputPath = join(projectRoot, "shared", "RimeData", "typing_pinyin.dict.yaml");
const expectedEntryCount = 65105;

interface SourceMetadata {
  sourceSha256: string;
  commit: string;
}

// 将锁定的 Apache-2.0 AOSP 原始词典转换为项目 Rime 词典，并严格校验来源哈希与行格式。
function generateDictionary(): void {
  const sourceMetadata = JSON.parse(readFileSync(sourceMetadataPath, "utf8")) as SourceMetadata;
  const sourceBuffer = readFileSync(sourcePath);
  const sourceHash = createHash("sha256").update(sourceBuffer).digest("hex");
  if (sourceHash !== sourceMetadata.sourceSha256) {
    throw new Error(`AOSP 拼音源文件哈希不匹配：${sourceHash}`);
  }

  const sourceText = sourceBuffer.toString("utf16le").replace(/^\uFEFF/, "");
  const dictionaryEntryList: string[] = [];
  for (const [lineIndex, sourceLine] of sourceText.split(/\r?\n/).entries()) {
    const trimmedLine = sourceLine.trim();
    if (!trimmedLine) continue;
    const tokenList = trimmedLine.split(/\s+/);
    if (tokenList.length < 4) {
      throw new Error(`AOSP 拼音词典第 ${lineIndex + 1} 行字段不足`);
    }
    const [textValue, frequencyText, gbkFlag, ...syllableList] = tokenList;
    if (!/^\d+(?:\.\d+)?$/.test(frequencyText) || !/^[01]$/.test(gbkFlag)) {
      throw new Error(`AOSP 拼音词典第 ${lineIndex + 1} 行频率或 GBK 标记无效`);
    }
    if (syllableList.some((syllableText) => !/^[a-z]+$/.test(syllableText))) {
      throw new Error(`AOSP 拼音词典第 ${lineIndex + 1} 行包含无效拼音`);
    }
    if ([...textValue].length !== syllableList.length) {
      throw new Error(`AOSP 拼音词典第 ${lineIndex + 1} 行字数与拼音数不一致`);
    }
    const weightValue = Math.max(1, Math.round(Number(frequencyText)));
    dictionaryEntryList.push(`${textValue}\t${syllableList.join(" ")}\t${weightValue}`);
  }
  if (dictionaryEntryList.length !== expectedEntryCount) {
    throw new Error(`AOSP 拼音词典条目数异常：${dictionaryEntryList.length}`);
  }

  const outputText = [
    "# Rime dictionary",
    "# encoding: utf-8",
    "# Generated by scripts/rime/generate-aosp-pinyin-dictionary.ts.",
    `# Source: AOSP PinyinIME ${sourceMetadata.commit}, Apache-2.0; see vendor/aosp-pinyinime-data/NOTICE.`,
    "",
    "---",
    "name: typing_pinyin",
    'version: "2026.08.05"',
    "sort: by_weight",
    "use_preset_vocabulary: false",
    "columns:",
    "  - text",
    "  - code",
    "  - weight",
    "...",
    "",
    ...dictionaryEntryList,
    "",
  ].join("\n");
  writeFileSync(outputPath, outputText);
  console.log(`已生成 ${dictionaryEntryList.length} 条 Apache-2.0 拼音词条：${outputPath}`);
}

generateDictionary();
